sudo: required

services:
  - docker

before_install:
  - docker build -t awesometeamplayer/rabbit-mq .

script:
  - echo "hello"

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" hub.docker.com;
    docker push awesometeamplayer/rabbit-mq;
    fi
